source 'http://rubygems.org'

gem 'rails', '2.3.5'
gem 'activesupport', '2.3.5'
gem 'authlogic', '2.1.2'
gem 'builder', '3.0.0'
gem 'curb'
gem 'database_cleaner'
gem 'hoe', '2.8.0'
gem 'libxml-ruby', '1.1.3'
gem 'marc', '0.3.0'
gem 'mysql', '2.8.1'
gem 'nokogiri', '1.4.3.1'
gem 'parslet', '1.2.0'
gem 'prawn', '0.8.4'
gem 'prawn-core', '0.8.4'
gem 'prawn-layout', '0.8.4'
gem 'prawn-security', '0.8.4'
gem 'rack'
gem 'rcov'
gem 'rest-client', '1.6.1'
gem 'rsolr', '0.12.1'
gem 'rsolr-ext', '0.12.0'
gem 'ruby-net-ldap', '0.0.4'
gem 'rubytree', '0.5.2'
gem 'ruby-xslt', '0.9.6'
gem 'unicode', '0.3.1'
gem 'will_paginate', '2.3.11'
gem 'nokogiri-happymapper', :git => "git://github.com/burtlo/happymapper.git", :branch => 'unhappymapper-nokogiri'
gem 'fastercsv'
gem 'fakeweb'
gem 'mocha'
gem 'cucumber', '1.0.2'
gem 'cucumber-rails'
gem 'gherkin', '2.4.5'
gem 'webrat'
gem 'rspec', '<2.0.0'  
gem 'rspec-rails', '<2.0.0' # rspec-rails 2.0.0 requires Rails 3.
