home_locations:
  "UVA-LIB": "UVA Library"
  "ALDERMAN": "Alderman"
  "CLEMONS": "Clemons"
  "FINE-ARTS": "Fine Arts"
  "SCI-ENG": "Brown Science & Engineering"
  "BIO-PSYCH": "Biology & Psychology (Bio-Psych)"
  "CHEMISTRY": "Chemistry"
  "MATH": "Math"
  "PHYSICS": "Physics"
  "SPEC-COLL": "Special Collections"
  "EDUCATION": "Education"
  "MUSIC": "Music"
  "DARDEN": "Darden"
  "IVY": "Ivy Stacks"
  "ASTRONOMY": "Astronomy"
  "MT-LAKE": "Mountain Lake"
  "LAW": "Law"
  "BLANDY": "BLANDY"
  "HEALTHSCI": "Health Sciences"
  "MEDIA-CTR": "Robertson Media Center"
  "ATSEA": "Semester at Sea"
  "LEO": "Leo Library"
  

current_locations:
  "SC-TECH": "Special Collections SC-TECH"
  "CHECKEDOUT": "CHECKED OUT"
  "UL-PRESERV": "ZZZ Preservation"
  "ON-ORDER": "Item is on order--Not yet received"
  "UNKNOWN": "ZZZ Loc. unknown at time of dataload"
  "BP-CIRCDSK": "Biology/Psychology Library Circ Desk"
  "ISSING": "Missing"
  "LOST": "ZZZ Item is lost"
  "BINDERY": "Item has been sent to the bindery"
  "IN-PROCESS": "Item being cataloged"
  "LOST-NRO": "ZZZ Item is lost--DO NOT RE-ORDER"
  "INTRANSIT": "Item in transit to home library"
  "ILL": "Interlibrary Lending"
  "CIRC-HOLD": "Item is on hold--Ask at circulation desk"
  "ED-JUV-REF": "Education Juvenile Reference"
  "RAREBKSCHL": "Rare Books School"
  "DA-MICFORM": "Darden Microforms"
  "ED-JUV-OVR": "Education Juvenile Oversize"
  "DA-CURRENT": "Darden Current Reading Collection"
  "DISCARD": "ZZZ Item record is being removed"
  "WITHDRAWN": "ZZZ Item withdrawn from collection"
  "UL-PRNTSVS": "ZZZ Printing Services"
  "CONT-ED-NV": "Continuing Education-No.Va.-Reserve"
  "CONT-ED-SW": "Continuing Education-SoWestVA-Reserve"
  "BARRED": "ZZZ Item billed for replacement"
  "BURSARED": "ZZZ Referred to Bursar for collection"
  "HS-PATFAM": "Health Sciences Patient & Family Health Collection"
  "CATALOGING": "Item intransit to cataloging for processing"
  "LOST-PAID": "$<LOCN_desc_lostpaid>"
  "LOSTCLOSED": "ZZZ Item is lost--Removed from collection"
  "PRESERVATN": "Item has been sent to Preservation"
  "ORD-CLOSED": "ZZZ Order closed (Ceased publication)"
  "SC-ARCHV": "Special Collections SC-ARCHV"
  "SC-ARCHV-X": "Special Collections SC-ARCHV-X"
  "SEL-MEDIA": "Research Computing Lab"
  "SE-TS-OFF": "ZZZ Brown Library Tech Serv Office"
  "AS-RESV": "Astronomy Library Reserves"
  "LOST-ASSUM": "ZZZ Assumed lost"
  "CONT-EDUC": "Continuing Education Office"
  "ATSEA-STKS": "Semester at Sea Collection"
  "LOST-CLAIM": "ZZZ Claims lost"
  "PHYS-SPEC": "Physics Library Special Collection"
  "CONT-ED-RO": "Continuing Education-Roanoke-Reserve"
  "ATSEA-RSRV": "Semester at Sea Reserve Collection"
  "U-LABEL": "Music Title Label Prep"
  "AL-SCHOLAR": "Scholars' Lab"
  "SC-STKS-D": "Special Collections On Deposit"
  "CHEM-BOX": "Chem Lib Book is Boxed - Ask Lib Staff"
  "AS-CIRCDSK": "Astronomy Library Circ Desk"
  "FA-REFARCV": "Fine Arts Ref. Architectural Archives"
  "G_S-ATLAS": "Map Room Atlases"
  "TLAKE": "Mt. Lake Biological Station Library"
  "LAW-HOLD": "Law On Hold"
  "LAW-BASEMT": "Law Basement"
  "LAW-CAREER": "Law Career Services"
  "LAW-FLOOR1": "Law First Floor"
  "LAW-FLOOR2": "Law Second Floor"
  "LAW-FLOOR3": "Law Third Floor"
  "LAW-IVY": "Law Ivy Storage"
  "LAW-PUBSER": "Law Public Services"
  "LAW1-RSRV": "Law 1st Floor Reserve Room"
  "LAW1-TAX": "Law 1st Floor Tax Alcove"
  "LAW2-DOCS": "Law 2nd Floor Documents"
  "LAB": ""
  "LAW2-FORGN": "Law 2nd Floor Foreign Law"
  "LAW2-INTL": "Law 2nd Floor Intl Law"
  "LAW2-KLAUS": "Law 2nd Floor Klaus Rr"
  "LAW2-MEDIA": "Law 2nd Floor Media"
  "LAW2-OCEAN": "Law 2nd Floor Oceans Law"
  "LAW2-REF": "Law 2nd Floor Reference"
  "LAW-FACOFF": "ZZZ Law Faculty Offices"
  "ATH-SPEC": "Math Library Special Collection"
  "AL-REQUEST": "Alderman Basement (use request item)"
  "DOC-READRM": "Alderman Gov Docs Reading Room"
  "AL-OVERSZE": "Alderman Oversize (Near New Stacks elevator)"
  "DOC-VA": "Alderman Gov Docs Virginia"
  "DOC-INTL": "Alderman Gov Docs International"
  "DOC-US": "Alderman Gov Docs U.S."
  "DOC-DESK": "Alderman Gov Docs Info Desk"
  "CUR-PER": "Current Periodicals"
  "OFFICE": ""
  "LAW3-SPCOL": "Law 3rd Floor Special Collections"
  "LAW2-TECSR": "Law 2nd Floor Tech. Services"
  "SE-EXHIBIT": "Science & Engr Library Exhibit"
  "SC-STKSXFF": "Special Collections SC-STKSXFF"
  "LAW-PAID": "ZZZ Law Payment Records"
  "BLANDY": "Blandy Farm Library"
  "DOC-OFFICE": "Alderman Gov Docs Office"
  "A-JOURNLS": "Math Library Journals"
  "HS-HOLDS": "Health Sciences Hold"
  "SC-MCGRXFF": "Special Collections SC-MCGRXFF"
  "GEOSTAT": "Map Room"
  "G_S-OFFICE": "Map Room Office"
  "ETEXT-CTR": "Electronic Text Center"
  "SC-BARRXFF": "Special Collections SC-BARRXFF"
  "HS-ADMIN": "Health Sciences Staff Book"
  "CDNETWORK": "Library CD-ROM Network (Online)"
  "INTERNET": "Internet materials"
  "HS-ATLASST": "Health Sciences Atlas Stand"
  "DAMAGED": "Item damaged--Use request item for ILL"
  "HS-BIBCONT": "Health Sciences Staff Book"
  "HS-BINDERY": "Health Sciences Bindery"
  "IVYANNEX": "Ivy Annex"
  "HS-BINDPRP": "Health Sciences Bindery Prep"
  "HS-BKSTCKS": "Health Sciences Bookstacks Book"
  "HS-BD96-97": "ZZZ Health Sciences Journal bound 96-97"
  "HS-BD97-98": "ZZZ Health Sciences Journal bound 97-98"
  "HS-BD98-99": "ZZZ Health Sciences Journal bound 98-99"
  "EXHIBIT": "Exhibit"
  "HS-BD99-00": "ZZZ Health Sciences Journal bound 99-00"
  "HS-BD2001": "ZZZ Health Sciences Journal bound 2001"
  "HS-BD2002": "ZZZ Health Sciences Journal bound 2002"
  "HS-BD2003": "ZZZ Health Sciences Journal bound 2003"
  "HS-BD2004": "ZZZ Health Sciences Journal bound 2004"
  "NEW_BOOKS": "New books shelf"
  "HS-BD2005": "ZZZ Health Sciences Journal bound 2005"
  "HS-CABELBK": "Health Sciences Cabell Book Stacks"
  "HS-CABELJR": "Health Sciences Cabell Journal Stacks"
  "HS-CHKDOUT": "Health Sciences checked-out"
  "HS-CIRCDPT": "Health Sciences Circulation Dept."
  "HS-CIRCDSK": "Health Sciences Circulation Desk"
  "HS-CLMRTD": "Health Sciences Claimed returned"
  "HS-CLENP00": "ZZZ Health Sciences Cleanup project"
  "HS-COLSERV": "Health Sciences Coll Dev"
  "LAW-STKS": "Law Stacks"
  "ASTRO-STKS": "Astronomy Library Stacks"
  "ATH-STKS": "Math Library Stacks"
  "ASTRO-REF": "Astronomy Library Reference"
  "ATH-REF": "Math Library Reference"
  "LAW2-RREF": "Law 2nd Floor Ready Reference"
  "LAW2-HPRES": "Law 2nd Floor Historic Preservation"
  "DEC-IND-RM": "Declaration of Independence Room"
  "HS-DOCDEL": "Health Sciences Doc Del"
  "REFERENCE": ""
  "HS-HISTCOL": "Health Sciences Hist Coll"
  "HS-ILL": "Health Sciences Interlibrary Loan"
  "RMC-RESV": "RMC reserves"
  "STACKS": ""
  "HS-INCOND": "Health Sciences Inconditional"
  "HS-REF": "Health Sciences Reference Shelves"
  "VAULT": ""
  "FOLIO": "Folio"
  "HS-INPROC": "Health Sciences In Processing"
  "EQUIPMENT": "Equipment Room"
  "STUDYROOM": "Study room"
  "HS-INTRANS": "Health Sciences In Transit"
  "HS-IVY": "Health Sciences Ivy"
  "GBP": "Google Books Project"
  "HS-JRLSTKS": "Health Sciences Journal Stack"
  "BROWSING": "Browsing"
  "BOUND": "Bound"
  "HS-LABELLG": "Health Sciences Labeling"
  "HS-LEISURE": "Health Sciences Browsing Shelves"
  "HS-LOCATE": "Health Sciences Items on Locate"
  "HS-LOST": "Health Sciences Lost Items"
  "HS-LRCSTKS": "Health Sciences LRC stacks"
  "HS-LRCDEPT": "Health Sciences LRC Dept"
  "HS-LRCDESK": "Health Sciences LRC Desk"
  "VA-REC-CTR": "Virginia State Records Center"
  "HS-LRCRSVE": "Health Sciences LRC Reserve"
  "HS-MISSING": "Health Sciences Missing Items"
  "HS-NETWRK": "Health Sciences items on local server"
  "FA-SLD-TST": "Fine Arts Slide Coll.  Test location"
  "HS-ONORDER": "Health Sciences items On Order"
  "AVAIL_SOON": "$<LOCN_desc_availsoon>"
  "HS-ONHOLD": "Health Sciences items On hold"
  "HS-ONLINE": "Health Sciences items Online"
  "INSHIPPING": "$<LOCN_desc_in_shipping>"
  "HS-OVERSZ": "Health Sciences Oversize shelves"
  "HS-RAREOVS": "Health Sciences Rare Oversize shelves"
  "HS-RARESHL": "Health Sciences Rare Shelves"
  "HS-RAREVLT": "Health Sciences Rare Vault"
  "HS-RECALLD": "Health Sciences Recalled"
  "DOC-OVERSZ": "Alderman Gov Docs Oversize"
  "HS-REFDEPT": "Health Sciences Ref. Dept"
  "HS-REFDESK": "Health Sciences Ref. Desk"
  "HS-REPAIR": "Health Sciences Repair"
  "HS-RESERVE": "Health Sciences Reserve"
  "HS-SYSDEPT": "Health Sciences Sys Dept"
  "HS-WD96/97": "ZZZ Health Sciences withdrawn 96/97"
  "HS-WD98/99": "ZZZ Health Sciences withdrawn 98/99"
  "HS-WD99/00": "ZZZ Health Sciences withdrawn 99/00"
  "HS-WD2001": "ZZZ Health Sciences withdrawn 2001"
  "HS-WD2002": "ZZZ Health Sciences withdrawn 2002"
  "HS-WD2003": "ZZZ Health Sciences withdrawn 2003"
  "HS-WD2004": "ZZZ Health Sciences withdrawn 2004"
  "HS-WD2005": "ZZZ Health Sciences withdrawn 2005"
  "HS-WED9798": "ZZZ Health Sciences weeded 97/98"
  "HS-WED2001": "ZZZ Health Sciences weeded 2001"
  "HS-WED2002": "ZZZ Health Sciences weeded 2002"
  "HS-WTHDRAW": "ZZZ Health Sciences withdrawn"
  "UL-NOTHELD": "ZZZ Received items which are not kept"
  "UL-CATDEPT": "ZZZ Cataloging Department (Office copy)"
  "HS-REF#1": "Health Sciences Ref. Sect. 1"
  "HS-REF#2": "Health Sciences Ref. Sect. 2"
  "HS-REF#3": "Health Sciences Ref. Sect. 3"
  "UL-ACQDEPT": "ZZZ Acquisitions Department (Office copy)"
  "UL-ILSDEPT": "ZZZ Interlibrary Services Dept. (Office copy)"
  "UL-SYSDEPT": "ZZZ Systems Department (Office copy)"
  "UL-ADMIN": "ZZZ Administration (Office copy)"
  "UL-SS-DEPT": "ZZZ Social Sciences Dept. (Office copy)"
  "UL-HUMDEPT": "ZZZ Humanities Department (Office copy)"
  "UL-RISDEPT": "ZZZ Reference Info. Ser. Dept. (Office copy)"
  "UL-SC-DEPT": "ZZZ Special Collections UL-SC-DEPT"
  "UL-FA-DEPT": "ZZZ Fine Arts Library (Office copy)"
  "UL-CL-DEPT": "ZZZ Clemons Library (Office copy)"
  "UL-ED-DEPT": "ZZZ Education Library (Office copy)"
  "UL-SE-DEPT": "ZZZ Brown Library Office copy"
  "UL-SUPPORT": "ZZZ Misc. acquisitions records"
  "HS-REF#4": "Health Sciences Ref. Sect. 4"
  "AL-CIRCOFF": "Alderman Library Circulation Office"
  "BY-REQUEST": "Ivy Stacks"
  "CH-ANNEX": "Chemistry Reference at Brown Library"
  "CL-OFFICE": "Clemons Robertson Media Office"
  "ALD-STKS": "Alderman Library Stacks"
  "AL-MICFORM": "Alderman Library Microforms"
  "AL-TIBET": "Alderman Library Tibetan Collection"
  "AL-LOCSTKS": "Alderman Library Locked Stacks"
  "AL-NEWSPAP": "Alderman Library Newspaper Collection"
  "AL-PER-RM": "Alderman Library Periodical Room"
  "AL-PERDSK": "Alderman Library Periodical Desk"
  "AL-REF": "Alderman Library Reference"
  "AL-READYRF": "Alderman Library Ready Reference"
  "AL-REFCLAS": "Alderman Library Reference Classroom"
  "CLEM-STKS": "Clemons Stacks"
  "CLEM-REF": "Clemons Reference"
  "HS-REF#5": "Health Sciences Ref. Sect. 5"
  "HS-REF#6": "Health Sciences Ref. Sect. 6"
  "HS-REF#7": "Health Sciences Ref. Sect. 7"
  "HS-REF#8": "Health Sciences Ref. Sect. 8"
  "CL-NEWSPAP": "Clemons Newspaper Collection"
  "CL-MEDIA": "Clemons Robertson Media Center"
  "CL-REFDSK": "Clemons Reference Desk"
  "CL-INDXTBL": "Clemons Index Table"
  "CL-ATLAS": "Clemons Atlas Stand"
  "CL-BROWSE": "Clemons Browsing Collection"
  "HS-REF#9": "Health Sciences Ref. Sect. 9"
  "U-STKS": "Music Stacks"
  "U-OVERSZE": "Music Oversize Shelves"
  "U-REF": "Music Reference"
  "U-INDXTBL": "Music Index Table (stacks)"
  "U-REFSTKS": "Music Reference Stacks"
  "U-OFFICE": "Music Office"
  "U-MICFORM": "Music Microforms"
  "U-CIRCDSK": "Music Circulation Desk"
  "U-MINI": "Music Miniature Scores"
  "FA-STKS": "Fine Arts Regular Stacks"
  "FA-FOLIO": "Fine Arts Folio Stacks"
  "FA-OVERSZE": "Fine Arts Oversize Stacks"
  "FA-MICFORM": "Fine Arts Microforms Reading Room"
  "FA-JOURNLS": "Fine Arts Journal Stacks"
  "FA-CIRCDSK": "Fine Arts Circulation Desk"
  "FA-RB-STKS": "Fine Arts Special Coll. Regular Stacks"
  "HS-REF#10": "Health Sciences Ref. Sect. 10"
  "HS-REF#11": "Health Sciences Ref. Sect. 11"
  "HS-REF#12": "Health Sciences Ref. Sect. 12"
  "FA-ATLAS": "Fine Arts Atlas Stand"
  "FA-RB-FOL": "Fine Arts Special Coll. Folio Stacks"
  "FA-RB-OVER": "Fine Arts Special Coll. Oversize Stacks"
  "FA-THESIS": "Fine Arts Theses and Dissertations"
  "HS-REF#13": "Health Sciences Ref. Sect. 13"
  "HS-REF#14": "Health Sciences Ref. Sect. 14"
  "HS-REF#15": "Health Sciences Ref. Sect. 15"
  "FA-REF": "Fine Arts Reference (1st floor)"
  "FA-SLIDES": "Fine Arts Slide Coll. Cataloged Slides"
  "FA-SLD-NB": "Fine Arts Slide Coll. Notebooks"
  "HS-REF#16": "Health Sciences Ref. Sect. 16"
  "HS-REF#17": "Health Sciences Ref. Sect. 17"
  "FA-SL-STKS": "Fine Arts Slide Coll. Stacks"
  "FA-SLD-PDG": "Fine Arts Slide Coll. Pidgeon Sets"
  "EDUC-STKS": "Education Stacks"
  "ED-JOURNLS": "Education Journals"
  "ED-CIRCDSK": "Education Circulation Desk"
  "ED-TS-OFF": "Education Technical Services Office"
  "ED-OFFICE": "Education Librarian's Office"
  "ED-OVERSZE": "Education Oversize"
  "ED-JUV": "Education Juvenile Collection"
  "ED-CIRCOFF": "Education Circulation Office"
  "EDUC-REF": "Education Reference"
  "ED-INDXTBL": "Education Reference"
  "ED-MICFORM": "Education Microform Room"
  "CHEM-STKS": "Chemistry Library Stacks"
  "CH-JOURNLS": "Chemistry Library Journals"
  "CHEM-REF": "Chemistry Reference"
  "CHEM-RESV": "Chemistry Library Reserves"
  "CH-CIRCDSK": "Chemistry Library Circ Desk"
  "SEL-STKS": "Brown Library Stacks"
  "SE-JOURNLS": "Brown Library Journals"
  "SE-LANDMKS": "Brown Library Microforms"
  "SE-OVERSZE": "Brown Library Oversize"
  "SEL-REF": "Brown Library Reference"
  "SE-REFDSK": "Brown Library Reference Desk"
  "SE-MICFORM": "Brown Library Microforms"
  "SE-CIRCDSK": "Brown Library Circulation Desk"
  "SE-OFF-DIR": "Brown Library Director's Office"
  "A-RESV": "Math Library Reserves"
  "A-CIRCDSK": "Math Library Circ Desk"
  "ASTRO-CHRT": "Astronomy Library Chart Room"
  "BP-STKS": "Biology/Psychology Library Stacks"
  "BP-JOURNLS": "Biology/Psychology Library Journals"
  "BP-REF": "Biology/Psychology Library Reference"
  "BP-RESV": "Biology/Psychology Library Reserves"
  "PHYS-STKS": "Physics Library Stacks"
  "PH-JOURNLS": "Physics Library Journals"
  "PHYS-REF": "Physics Library Reference"
  "PHYS-RESV": "Physics Library Reserves"
  "PH-CIRCDSK": "Physics Library Circ Desk"
  "SC-REF": "Special Collections SC-REF"
  "SC-STKS": "Special Collections SC-STKS"
  "SC-STKS-X": "Special Collections SC-STKS-X"
  "SC-STKS-XZ": "Special Collections SC-STKS-XZ"
  "SC-STKS-XF": "Special Collections SC-STKS-XF"
  "SC-STKS-M": "Special Collections SC-STKS-M"
  "SC-STKS-F": "Special Collections SC-STKS-F"
  "SC-STKS-FF": "Special Collections SC-STKS-FF"
  "SC-REF-F": "Special Collections SC-REF-F"
  "SC-TATUM": "Special Collections SC-TATUM"
  "SC-TATUM-F": "Special Collections SC-TATUM-F"
  "SC-TATUMFF": "Special Collections SC-TATUMFF"
  "SC-TATUM-M": "Special Collections SC-TATUM-M"
  "SC-TATUM-X": "Special Collections SC-TATUM-X"
  "SC-GARN-RM": "Special Collections SC-GARN-RM"
  "SC-GARN-F": "Special Collections SC-GARN-F"
  "SC-MCGR-RM": "Special Collections SC-MCGR-RM"
  "SC-MCGR-ST": "Special Collections SC-MCGR-ST"
  "SC-MCGR-F": "Special Collections SC-MCGR-F"
  "SC-MCGR-FF": "Special Collections SC-MCGR-FF"
  "SC-MCGR-X": "Special Collections SC-MCGR-X"
  "SC-MCGR-XF": "Special Collections SC-MCGR-XF"
  "SC-MCGR-XZ": "Special Collections SC-MCGR-XZ"
  "SC-BARR-RM": "Special Collections SC-BARR-RM"
  "SC-BARR-F": "Special Collections SC-BARR-F"
  "SC-IVY": "Special Collections SC-IVY -- Use request item"
  "SC-SCOTT": "Special Collections SC-SCOTT"
  "SC-SCOTT-F": "Special Collections SC-SCOTT-F"
  "SC-SCOTTFF": "Special Collections SC-SCOTTFF"
  "SC-SCOTT-M": "Special Collections SC-SCOTT-M"
  "SC-SCOTT-X": "Special Collections SC-SCOTT-X"
  "SC-SCOTTXF": "Special Collections SC-SCOTTXF"
  "SC-BARR-ST": "Special Collections SC-BARR-ST"
  "SC-BARR-M": "Special Collections SC-BARR-M"
  "SC-BARR-FF": "Special Collections SC-BARR-FF"
  "SC-BARR-X": "Special Collections SC-BARR-X"
  "SC-BARR-XF": "Special Collections SC-BARR-XF"
  "SC-BARR-XZ": "Special Collections SC-BARR-XZ"
  "DARD-STKS": "Darden Stacks"
  "DARD-REF": "Darden Reference"
  "SEL-RESV": "Brown Library Reserves"
  "DA-INDXTBL": "Darden Index Tables (Reference room)"
  "DA-PLACEMT": "Darden Placement Room"
  "DA-JOURNLS": "Darden Bound Journals"
  "DA-CIRCDSK": "Darden Circulation Desk"
  "AL-CIRCDSK": "Alderman Library Circulation Desk"
  "AL-REFATLS": "Alderman Library Reference Atlas"
  "AL-REFINDX": "Alderman Library Reference Index"
  "FA-RESV": "Fine Arts Reserve Materials"
  "EDUC-RESV": "Education Reserve Shelves"
  "U-RESV": "Music Reserves"
  "CLEM-RESV": "Clemons Reserves"
  "DARD-RESV": "Darden Reserve"
  "RSRVSHADOW": "ZZZ Reserve shadow"
  "DA-TURNER": "Darden Turner Coll. (leisure reading)"
  "CL-STORAGE": "ZZZ Clemons 201 storage room"
  "ORD-CANCLD": "ZZZ Canceled order"
  "FA-SLIDERF": "Fine Arts Slide Coll. Reference"
  "HS-REF#18": "Health Sciences Ref. Sect. 18"
  "HS-REF#19": "Health Sciences Ref. Sect. 19"
  "HS-REF#20": "Health Sciences Ref. Sect. 20"
  "HS-REF#21": "Health Sciences Ref. Sect. 21"
  "HS-REF#22": "Health Sciences Ref. Sect. 22"
  "HS-REF#23": "Health Sciences Ref. Sect. 23"
  "HS-REF#24": "Health Sciences Ref. Sect. 24"
  "HS-REF#25": "Health Sciences Ref. Sect. 25"
  "HS-REF#26": "Health Sciences Ref. Sect. 26"
  "HS-REF#27": "Health Sciences Ref. Sect. 27"
  "HS-REF#28": "Health Sciences Ref. Sect. 28"
  "HS-REF#29": "Health Sciences Ref. Sect. 29"
  "HS-REF#30": "Health Sciences Ref. Sect. 30"
  "HS-WD97/98": "ZZZ Health Sciences withdrawn 97/98"
  "HS-COVLOC": "ZZZ Health Sciences Cover records"
  "SC-STKS-EF": "Special Collections SC-STKS-EF"

